### ISSUE TITLE
Add Contributing.md File

### ISSUE THREAD

**Issue by amitkumar-y** [simpletwitter/simpletwitter#17]
Having contributing.md file will help new users to start their contribution.
You can assign this to me I will add the file.

**Comment by pravee42** [comment]
Sure you can add this

**Comment by Ratikant-rout** [comment]
Am Thinking To Add A Contribution File Rule As Well As Github Commands Can You Please Assing Me @amitkumar-y ? I Would be SO Much Glad To Contribute

**Comment by Ratikant-rout** [comment]
Am Thinking To Add A Contribution File Rule As Well As Github Commands Can You Please Assing Me @pravee42 ? I Would be SO Much Glad To Contribute

**Comment by Ratikant-rout** [comment]
Thanks
